### ISSUE TITLE
PIM Documentation is very outdated and new structure is very weird, also /forum missing... (3.x)

### ISSUE THREAD

**Issue by Reiner030** [akeneo/pim-community-dev#10836]
https://docs.akeneo.com/3.1/technical_architecture/technical_information/operation_processes.html#backup-management

* With this setup:
  > Two pieces of information should be backed up:
  > 
  > * database data: When using a MySQL server we recommend using the mysqldump tool with the –single-transaction option.
  > * files and media data (uploaded and archived): This data can be found in the upload_dir and archive_dir (as defined in the app/config/pim_parameters.yml file). No specific backup tool is recommended for this task.

  I get after restore in export jobs to shopify dev store many missing errors like:
  > *WARNING*
  > The media has not been copied. The file "9/f/0/c/9f0cabb2d301b383890e7a24ad21a20542e08717_18385.jpg" is not present on the filesystem.
  > _Display item_
  which are gone when I am rsyncing / also backup/restore files to `app/file_storage` folder.
  There is also no documentation howto files in this path could be regenerated e.g. out of the archive folders and the `uploads` folder which is also every time empty when I am checking it.
  
* Elasticache also isn't mentioned to reindex after Restore as written in:
https://github.com/akeneo/ExtendedAttributeTypeBundle/issues/59#issuecomment-380123507
  or also https://webkul.com/blog/elastic-indexes-akeneo/
  
So documentation must be very incomplete for changes in 2.x/3.x.

BTW: Also many matches in Google Matches to different queries shows old forum entries which are all redirected to your main website/common "feature" pages which are not helpful... 
To which URL is the /forum relocated or was it dropped ? 
This is also the reason I write this "issue" here and not there... 

Bests
Reiner

**Comment by jmleroux** [comment]
Hello @Reiner030 ,

Do you still have the same issues with more recent Akeneo version?

**Comment by Reiner030** [comment]
Sorry, I have sadly overseen the question last year because of to much "spammy" update mails and just found it again while searching again for "which folder needs to be backup Akeneo 3.2 4.0 5.0" just after:
https://docs.akeneo.com/4.0/technical_architecture/technical_information/operation_processes.html
https://docs.akeneo.com/3.1/install_pim/manual/system_requirements/system_requirements.html
https://docs.akeneo.com/2.0/cloud_edition/flexibility_mode/docs/backups_management.html

What do you think with letting own Akeneo knowledge beside if this question is answered even if you use 5.0 documentation?
https://docs.akeneo.com/5.0/import_and_export_data/index.html
=> there is the information that the initial import can be done by replacing "minimal" CSV files with own content but nowhere is documented howto create this content e.g. from an older Akeneo setup.

When I am searching for "backup" in your documentation I got reference to "Backup Management":
https://docs.akeneo.com/5.0/technical_architecture/technical_information/operation_processes.html#backup-management
with:
```
Two pieces of information should be backed up:
- database data: When using a MySQL server we recommend using the mysqldump tool with the –single-transaction option.
- files and media data (uploaded and archived): This data can be found in the upload_dir and archive_dir (as  defined in the app/config/pim_parameters.yml file). No specific backup tool is recommended for this task.
...
```

which looks to be solved my initial issue mention.

**Problem is only that since 4.0 there isn't anymore a pim_parameters file...**

And checking your referenced upgrade script 
./vendor/akeneo/pim-community-dev/std-build/migration/prepare_32_to_40.sh
I find there these paths as important ones (and not in documentation mentioned upload_dir and archive_dir)
```
./vendor/akeneo/pim-community-dev/std-build/migration/32_to_40/oneup_flysystem.yml
oneup_flysystem:
    adapters:
        catalog_storage_adapter:
            local:
                directory: '%kernel.project_dir%/app/file_storage/catalog'
        jobs_storage_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/jobs'
        archivist_adapter:
            local:
                directory: '%kernel.project_dir%/app/archive'
```

Removing Vendor and logging/backups from result my search for the documented folder in testing 3.2 is also very lonely:

```
akeneo@akeneo-testing:/var/www/pim-community-standard$ find . | grep --color=always -e uploads -e archive | grep -v -e vendor -e var/log -e upgrades -e .tgz
./app/uploads
./app/uploads/product
./app/archive

```

And even the production based Akeneo 3.1 instance has no content in these folders which needs a backup ?

```
akeneo@akeneo01:/var/www/pim-community-standard$ find -L . | grep --color=always -e uploads -e archive | grep -v -e vendor -e var/log -e upgrades -e .tgz -e app/storage
find: ‘./app/storage/lost+found’: Permission denied
./app/uploads.orig
./app/uploads.orig/product
./app/uploads
./app/uploads/product
./app/archive
./app/archive/export
./app/archive/export/xlsx_product_model_export
./app/archive/export/xlsx_product_model_export/351940
./app/archive/export/xlsx_product_model_export/351940/output
./app/archive/export/xlsx_product_model_export/351940/output/BI_Export_Product_Model_XLSX_2021-09-08_20-45-09.xlsx
...
./app/archive/export/xlsx_product_export
./app/archive/export/xlsx_product_export/351922
./app/archive/export/xlsx_product_export/351922/output
./app/archive/export/xlsx_product_export/351922/output/BI_Export_Product_XLSX_2021-09-06_20-50-03.xlsx
...
./app/archive/export/xlsx_product_export/351982
./app/archive/export/xlsx_product_export/351982/output
./app/archive/export/xlsx_product_export/351982/output/export_Export_Product_XLSX__all_locales__2021-09-10_15-00-24.xlsx
./web/bundles/pimui/templates/job-execution/download-archives-buttons.html
./web/bundles/pimui/js/job/execution/download-archives-buttons.js
```


So from upgrade path / found files it seems that nearby database dump the only folder which needs really a backup is:

```
./vendor/akeneo/pim-community-dev/std-build/migration/32_to_40/oneup_flysystem.yml
oneup_flysystem:
        catalog_storage_adapter:
            local:
                directory: '%kernel.project_dir%/app/file_storage/catalog'

```
till 3.2 and since 4.0 than:
```
        catalog_storage_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/catalog'
```

which is defined in pim-community-dev/config/packages/prod/oneup_flysystem.yml:
```
oneup_flysystem:
    adapters:
        asset_storage_adapter:
            nulladapter: ~
        catalog_storage_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/catalog'
        jobs_storage_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/jobs'
        archivist_adapter:
            local:
                directory: '%kernel.project_dir%/var/file_storage/archive'
```
???
