### ISSUE TITLE
Datagrid not visible on frontend

### ISSUE THREAD

**Issue by vasik-bukhari** [akeneo/pim-community-dev#11448]
**I'm reporting a Bug**

`Akeneo version 3.2.3`

I have been working on custom entity which I have created using CLI and also created CRUD using CLI.

I have now created a custom datagrid in src/Barcodes/Bundle/AppBundle/Resources/config/datagrid/barcodes-pricingrule.yml

```
datagrid:
    barcodes-pricingrules-grid:
        extended_entity_name: Barcodes\Bundle\AppBundle\Entity\Pricingrule
        options:
            entityHint: Pricingrule
            manageFilters: false
        source:
            # acl_resource: pim_user_user_index
            type: orm
            entity: 'Barcodes\Bundle\AppBundle\Entity\Pricingrule'
            query:
                select:
                    - pl.id
                    - pl.manufacturer
                    - pl.category
                    - pl.product
                    - pl.pricetype
                    - pl.operator
                    - pl.value
                    - pl.channel
                    - pl.createdAt
                    - pl.updatedAt
                from:
                    - { table: 'Barcodes\Bundle\AppBundle\Entity\Pricingrule', alias: pl }
        columns:
            id:
                label: 'id'
                frontend_type: label
            manufacturer:
                label: 'manufacturer'
            category:
                label: 'category'
            product:
                label: 'product'
            pricetype:
                label: 'pricetype'
            operator:
                label: 'operator'
            value:
                label: 'value'
            channel:
                label: 'channel'
            createdAt:
                label: 'createdAt'
            updatedAt:
                label: 'updatedAt'
        properties:
            id: ~
            update_link:
                type: url
                route: barcodes_pricingrules_edit
                params:
                    identifier: id
            delete_link:
                type: url
                route: barcodes_pricingrules_delete
                params:
                    identifier: id
        sorters:
            columns:
                id:
                    data_name: pl.id
                manufacturer:
                    data_name: pl.manufacturer
                category:
                    data_name: pl.category
                product:
                    data_name: pl.product
                pricetype:
                    data_name: pl.pricetype
                operator:
                    data_name: pl.operator
                value:
                    data_name: pl.value
                channel:
                    data_name: pl.channel
                createdAt:
                    data_name: pl.createdAt
                updatedAt:
                    data_name: pl.updatedAt
            default:
                id: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                product:
                    type: search
                    data_name: pl.product
                channel:
                    type: string
                    data_name: pl.channel
                category:
                    type: string
                    data_name: pl.category
                manufacturer:
                    type: string
                    data_name: pl.manufacturer
        actions:
            update:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:          navigate
                label:         pim_common.update
                link:          update_link
                rowAction:     true
            delete:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--trash
                type:          delete
                label:         pim_common.delete
                link:          delete_link
                # acl_resource:  pim_user_user_remove
```

I have called the grid in my form-extension as below
```
barcodes-pricingrules-index-pagination:
        module: oro/datagrid/pagination-input
        parent: barcodes-pricingrules-index-grid-container
        targetZone: toolbar
        config:
            gridName: barcodes-pricingrules-grid

    barcodes-pricingrules-index-grid:
        module: pim/form/common/index/grid
        parent: barcodes-pricingrules-index-grid-container
        position: 1000
        config:
            alias: barcodes-pricingrules-grid
```

there is one row manually added in data table as below
![image](https://user-images.githubusercontent.com/57760809/72795700-12524880-3c64-11ea-9dee-89456265848b.png)

executed the following commands:

```
php bin/console cache:clear --no-warmup --env=prod

bin/console pim:installer:dump-require-paths; bin/console pim:install:assets; bin/console assets:install --symlink; yarn run less; yarn run webpack
```

But the grid is empty on front end. See below image
![image](https://user-images.githubusercontent.com/57760809/72795937-770da300-3c64-11ea-98b4-0ee6eac3763c.png)
