### ISSUE TITLE
Unable to add new property to my custom entity

### ISSUE THREAD

**Issue by vasik-bukhari** [akeneo/pim-community-dev#11606]
**I'm reporting an issue**

For version = 3.2.3

I am unable to add new property to my custom entity.
Below is the entry added in my entity class:
```
/**
     * @var string|null
     */
    private $override_formula;
    /**
     * Set overrideFormula.
     *
     * @param string|null $overrideFormula
     *
     * @return Pricingrule
     */
    public function setOverrideFormula($overrideFormula = null)
    {
        $this->override_formula = $overrideFormula;
        return $this;
    }
    /**
     * Get overrideFormula.
     *
     * @return string|null
     */
    public function getOverrideFormula()
    {
        return $this->override_formula;
    }
```
New entry in my orm file:
```
        override_formula:
            type: string
            length: '255'
            nullable: true
```
Grid:
```
source:
            acl_resource: barcodes_pricingrule_index
            type: orm
            entity: 'Barcodes\Bundle\AppBundle\Entity\Pricingrule'
            query:
                select:
                    - pl.id
                    - pl.manufacturer
                    - pl.category
                    - pl.product
            ####Below line is causing the issue####
                    - pl.override_formula
                    - pl.pricetype
                    - pl.operator
                    - pl.price_value
                    - pl.channel
                    - pl.createdAt
                    - pl.updatedAt
```
getting the following error:

> [2020-02-19 21:49:30] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 59 near 'override_formula,': Error: Class Barcodes\Bundle\AppBundle\Entity\Pricingrule has no field or association named override_formula" at /opt/bitnami/apps/akeneo/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 65 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 59 near 'override_formula,': Error: Class Barcodes\\Bundle\\AppBundle\\Entity\\Pricingrule has no field or association named override_formula at /opt/bitnami/apps/akeneo/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:65, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT pl.id, pl.manufacturer, pl.category, pl.product, pl.override_formula, pl.pricetype, pl.operator, pl.price_value, pl.channel, pl.createdAt, pl.updatedAt FROM Barcodes\\Bundle\\AppBundle\\Entity\\Pricingrule pl at /opt/bitnami/apps/akeneo/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43)"} []

Refreshed cache, removed contents for var/cache, restarted apache, restarted elasticsearch, rebooted entire server. Still the above error is same.

But after orm file changed the column in update for the respective datatable in database.

Also after adding the manual entry in database I am getting the null response for override_formula:
 means my normalizer is also unable to get the value for this column from database.

![image](https://user-images.githubusercontent.com/57760809/74907786-10ea7c00-53da-11ea-9e96-4c4fa57d30df.png)

Below is the entry in database:
![image](https://user-images.githubusercontent.com/57760809/74907978-94a46880-53da-11ea-8277-cadbc1d97dec.png)

Do I have to run the commands :
`php bin/console --env=prod doctrine:migration:diff`
and
`php bin/console --env=prod doctrine:migrations:migrate`
???
I am not sure what these commands would do.
