### ISSUE TITLE
Error with Model\Group::getRoles() after a custom change

### ISSUE THREAD

**Issue by FrancoisSmile** [akeneo/pim-community-dev#13010]
:bug: **I'm reporting a Bug** :bug:

Hello there ! 
I am facing a problem during a custom development. I'm using latest version of Akeneo EE (4.0.64) with docker locally.
I need to override the `Group` entity to add a `Channel` property , and for this, my `oro_access_group` table is correctly update : I get my `channel_id`. (I followed this [doc](https://docs.akeneo.com/4.0/manipulate_pim_data/category/add_new_properties_to_a_category.html#configure-the-mapping-override))

But after this, many actions of Akeneo (some commands, sign in ...) throw this error (eg with `pimee:franklin-insights:init-franklin-user`) : 

```
root@33e863b38f01:/srv/pim# bin/console pimee:franklin-insights:init-franklin-user -v
14:47:44 ERROR     [console] Error thrown while running command "pimee:franklin-insights:init-franklin-user -v". Message: "Return value of Akeneo\UserManagement\Component\Model\Group::getRoles() must implement interface Doctrine\Common\Collections\Collection, null returned" ["exception" => TypeError { …},"command" => "pimee:franklin-insights:init-franklin-user -v","message" => "Return value of Akeneo\UserManagement\Component\Model\Group::getRoles() must implement interface Doctrine\Common\Collections\Collection, null returned"]

In Group.php line 76:
                                                                                                                                                          
  [TypeError]                                                                                                                                             
  Return value of Akeneo\UserManagement\Component\Model\Group::getRoles() must implement interface Doctrine\Common\Collections\Collection, null returned  
                                                                                                                                                          

Exception trace:
  at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/UserManagement/Component/Model/Group.php:76
 Akeneo\UserManagement\Component\Model\Group->getRoles() at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/UserManagement/Component/Model/User.php:643
 Akeneo\UserManagement\Component\Model\User->getRoles() at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/UserManagement/Bundle/Security/SystemUserToken.php:28
 Akeneo\UserManagement\Bundle\Security\SystemUserToken->__construct() at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/UserManagement/Bundle/EventListener/CreateUserSystemListener.php:76
 Akeneo\UserManagement\Bundle\EventListener\CreateUserSystemListener->createUserSystem() at /srv/pim/vendor/symfony/event-dispatcher/EventDispatcher.php:304
 Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}() at /srv/pim/vendor/symfony/event-dispatcher/EventDispatcher.php:264
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /srv/pim/vendor/symfony/event-dispatcher/EventDispatcher.php:239
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /srv/pim/vendor/symfony/event-dispatcher/EventDispatcher.php:73
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /srv/pim/vendor/symfony/console/Application.php:1024
 Symfony\Component\Console\Application->doRunCommand() at /srv/pim/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /srv/pim/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /srv/pim/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/pim/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /srv/pim/bin/console:36
```

Here is my custom `Group` entity :
```
use Akeneo\UserManagement\Component\Model\Group as BaseGroup;
class Group extends BaseGroup
{
    /** @var ChannelInterface */
    protected $channel;

    /**
     * @return ChannelInterface
     */
    public function getChannel() : ?ChannelInterface
    {
        return $this->channel;
    }

    /**
     * @param ChannelInterface $channel
     */
    public function setChannel(ChannelInterface $channel) : void
    {
        $this->channel = $channel;
    }
} 
```
Here is my `Group.orm.yml` :
```
XXXX\ChannelsRulesBundle\Entity\Group:
    type: entity
    table: oro_access_group
    changeTrackingPolicy: DEFERRED_EXPLICIT
    repositoryClass: Akeneo\UserManagement\Bundle\Doctrine\ORM\Repository\GroupRepository
    manyToMany:
      roles:
        targetEntity: Akeneo\UserManagement\Component\Model\Role
        joinTable:
          name: oro_user_access_group_role
          joinColumns:
            group_id:
              referencedColumnName: id
              onDelete: CASCADE
          inverseJoinColumns:
            role_id:
              referencedColumnName: id
              onDelete: CASCADE
    manyToOne:
      channel:
        targetEntity: Akeneo\Channel\Component\Model\Channel
        joinColumns:
          channel_id:
            referencedColumnName: id
            onDelete: 'SET NULL'
```
Here is my `entities.yml` :
```
parameters:
    pim_user.entity.group.class: XXXX\ChannelsRulesBundle\Entity\Group
```
Here is my `services.yml` :
```
akeneo_storage_utils:
    mapping_overrides:
        -
            original: Akeneo\UserManagement\Component\Model\Group
            override: Norauto\ChannelsRulesBundle\Entity\Group
```
After several days of blocking, I'm posting this issue.
Let me know if you need more informations.

Thanks,
François
