### ISSUE TITLE
Please remove redundant problematic variables in docker-compose.yml

### ISSUE THREAD

**Issue by adriancuadrado** [akeneo/pim-community-dev#14305]
:bug: **I'm reporting a Bug** :bug:

It's not really a bug, but I think it would be much better if you fix it:
When I edit the APP_ENV and XDEBUG_MODE environment variables in my .env.local and I create a new extra variable as follows:
```
APP_ENV=dev
XDEBUG_MODE=debug
MY_ENV_VARIABLE=a_value
```
And then run a Symfony command that I create to print the values of those variables...
```
docker-compose run -u www-data --rm php php bin/console app:my-command
```
I get the following values:
```
APP_ENV=prod
XDEBUG_MODE=off
MY_ENV_VARIABLE=a_value
```
The APP_ENV and XDEBUG_MODE variables are ignored, but not the MY_ENV_VARIABLE. This is so because the exported environment variables have precedence over those defined in .env and in .env.local.
If you take a look at the docker-compose.yml file, you will see this:
```
services:
  php:
    image: 'akeneo/pim-php-dev:5.0'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=pim-docker-cli'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: 'client_host=172.17.0.1'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
```
docker-compose only reads .env and not .env.local and then executes the command passing the environment defined under `environment:`. Once the script is executed, because APP_ENV=prod and XDEBUG_MODE=off are defined in the environment that docker-compose provided to the command, they end up overriding the .env.local values (because those variables, while executing the command, are not read from .env or .env.local, but from the environment).

My suggestion: Please remove the APP_ENV and XDEBUG_MODE environment variables from docker-compose. They are already defined in .env and is redundant and they will only cause problems like the one I mentioned above.
