### ISSUE TITLE
the ui not showing for the new connector AcmeXmlConnector

### ISSUE THREAD

**Issue by codermug** [akeneo/pim-community-dev#15170]
I'm using the CE 5.0.0 (used Docker for installation) and I have followed https://docs.akeneo.com/5.0/import_and_export_data/guides/product-import-from-xml-file.html
to create my first connector, the "Show" and "Edit" page not showing after creating xml import profile, it show a blank page only, with no JS errors! 
 
<img width="507" alt="Screen Shot 2021-08-23 at 8 23 43 PM" src="https://user-images.githubusercontent.com/5511060/130536258-1251f046-bcdc-41d6-b832-cc1da6181785.png">

**Comment by adrienlucas** [comment]
Hey @codermug I got into the same issue ^^

If like me you followed the documentation [here](https://docs.akeneo.com/latest/import_and_export_data/guides/product-import-from-xml-file.html) you can "fix" by changing the `xml_product_import` value at the `acme_xml_connector.job.job_parameters.provider.simple_xml_product_import` service definition by something like this :
```yaml
    acme_xml_connector.job.job_parameters.provider.simple_xml_product_import:
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
        arguments:
            -
#                xml_product_import: pim-job-instance-xml-product-import
                xml_product_import: pim-job-instance-csv-base-import
```

**Why ?**
AFAIS the previously declared frontend "extension" does not exists until you declared a `form_extensions` config file (which correspond, in the doc, to the two unexplained yaml blocks right after the `SimpleXmlImport` class content).  
If you use bundles (as the documentation suggests) **you should be fine copying those two yaml contents and merging them at `src/YourBundle//Resources/config/form_extensions.yml`.**

**But..**
If you don't use bundles in your `src` folder... I wanted to make a joke like "Hey Akeneo, 2017 called and it want its Symfony structure back" but I'm new here so...  

**So I'm not sure how to declare my own frontend extensions in a bundle-less context.** Maybe I missed something, sorry if it's the case.
