### ISSUE TITLE
Akeneo 6: Doctrine Entities Mapping shows error

### ISSUE THREAD

**Issue by ibs83278** [akeneo/pim-community-dev#16484]
:bug: **I'm reporting a Bug** :bug:
It ist a fresh installation of Akeneo 6 with Ubuntu 20.04.
The Symfony Profiler shows this error:
![Akeneo_6_issue](https://user-images.githubusercontent.com/69475130/157051446-00b5737b-45d2-4d5a-a92b-0fd982d0b376.jpg)

Does anybody know how to deal with this message? 
Thanks!

**Comment by XzAeRo** [comment]
Same issue happening at v6.0.40 (latest stable).

I haven't run into any errors yet, but still annoying.

Problem comes from these 2 files: 

- https://github.com/akeneo/pim-community-dev/blob/v6.0.40/src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Group.orm.yml
- https://github.com/akeneo/pim-community-dev/blob/v6.0.40/src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml

And the obvious issue is that there's a inverse side field set in Product.orm while there's no inverse in Group.

I'm not too knowledgable to know if this is a left-over problem form previous configurations...

**Comment by mautz-et-tong** [comment]
See https://github.com/akeneo/pim-community-dev/issues/19387 for a fix:
add to /src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Group.orm.yml
```
    manyToMany:
        products:
            targetEntity: Akeneo\Pim\Enrichment\Component\Product\Model\ProductInterface
            mappedBy: groups
```
