### ISSUE TITLE
New attribut type (sort of collection type)

### ISSUE THREAD

**Issue by arnolanglade** [akeneo/pim-community-dev#1704]
I created a new attribute which is a collection of files. Those files are not a simple ProductMedia, I extends this model and I added an extra property (a boolean). The form type is corectly rendered, I can add and remove items (I used the javascript provided bu the oroplateform).

When I try to save my collection, it happens something very strange! I can not delete the last item, it is the same when I want to remove the entire collection. When I try to update the boolean, a ducplication is created.

FYI, this attribute is localizable, I use MongoDB shell version: 2.4.10. My doctrine mapping is 

``` yaml
Pim\CatalogBundle\Document\ProductMedia:
    type: embeddedDocument
    fields:
        id:
            id: true
        filename:
            type: string
        filePath:
            type: string
        originalFilename:
            type: string
        mimeType:
            type: string
        public:
            type: boolean

Pim\CatalogBundle\Document\ProductValue:
    type: embeddedDocument
    fields:
    # ...
        medias:
            embedded: true
            cascade: all
            type: many
            targetDocument: Vendor\Pim\CatalogBundle\Document\ProductMedia
```

My attribute definition

``` yaml
    vendor_pim_catalog.attributetype.multifile:
        class: %vendor_pim_catolog.attributetype.multifile.class%
        arguments:
            - medias
            - vendor_pim_enrich_multiple_media
            - '@pim_catalog.validator.constraint_guesser.chained_attribute'
        tags:
            - { name: pim_catalog.attribute_type, alias: vendor_pim_catalog_multifile, entity: %pim_catalog.entity.product.class% }
```

Do you know what happens? Thanks !
