### ISSUE TITLE
Broken doctrine mapping

### ISSUE THREAD

**Issue by andriusvo** [akeneo/pim-community-dev#18888]
:bug: **I'm reporting a Bug** :bug:

Version - Akeneo PIM v7.0
Symfony Webprofiler shows invalid entity on `Akeneo\Pim\Enrichment\Component\Product\Model\Product`:

In a Group.orm.yml missed inverse side mapping:
```
    manyToMany:
        products:
            targetEntity: Akeneo\Pim\Enrichment\Component\Product\Model\Product
            mappedBy: groups
```
