### ISSUE TITLE
JobInstanceController storage type

### ISSUE THREAD

**Issue by andriusvo** [akeneo/pim-community-dev#18924]
:bug: **I'm reporting a Bug** :bug:

Affected versions: >= 7.0

In the controller `Akeneo\Platform\Bundle\ImportExportBundle\Controller\InternalApi\JobInstanceController` line 338, the code is trying to access `storage` parameters. F.e. if I defined a job, which is `export` and is doing things in the background, so I don't have to specify this key `storage` on a job configuration. Even if I specify the `storage` key:

```
    test_job:
        connector: Akeneo connector
        alias: test_alias
        label: Produce
        type: export
        configuration:
            storage:
                type: none
```

While loading fixtures there is an error that "The key "storage" was not expected"
