### ISSUE TITLE
Fixtures format consistency

### ISSUE THREAD

**Issue by aRn0D** [akeneo/pim-community-dev#2005]
The structure of the file `attribute_options.yml` is a bit different than 'attributes.yml' for example 
```yaml
attributes:
    sku: # code...
        labels:
            fr_FR: SKU
```
You need to repeat the code two times
```yaml
options:
    210_x_1219_mm:
        code: 210_x_1219_mm
```

Do CSV is supported by the installer? I speak about the attribute options.
