### ISSUE TITLE
Support arm64 platforms for Akaneo container images

### ISSUE THREAD

**Issue by noahschechter** [akeneo/pim-community-dev#20440]
:wrench: **I'm submitting a Feature Request** :wrench:

We are running a kubernetes cluster and we are strictly running on arm64 nodes. We noticed that this would make the community edition incompatible with our cluster, unless we introduce a compatible node. 

https://hub.docker.com/r/akeneo/node/tags
https://hub.docker.com/r/akeneo/pim-php-dev/tags

Images like the above are built to only run on x86 platforms.

It would be amazing to have support for arm64 platforms as well!

**Comment by mauricios** [comment]
Adding a data point for anyone hitting this on Apple Silicon (M-series) Macs, plus a working stopgap until native arm64 images exist.

The subtle part: forcing linux/amd64 globally is not enough

The workaround is `export DOCKER_DEFAULT_PLATFORM=linux/amd64` so the amd64-only Akeneo images (pim-php-dev, node) run under emulation. But that also forces Elasticsearch under QEMU, where ES 8.x dies at boot:

```
fatal exception while booting Elasticsearch
java.lang.UnsupportedOperationException: seccomp unavailable:
CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
    at org.elasticsearch.nativeaccess.LinuxNativeAccess.tryInstallExecSandbox(...)
```

ES 8 installs a seccomp-based exec sandbox at startup and, unlike ES 7, provides no supported way to disable it, so under emulation it hard-fails and the installer times out waiting for it.

Workaround: pin the platform per service, not globally

Only the Akeneo-published images are amd64-only. Elasticsearch, MySQL, MinIO, httpd, blackfire all have native arm64 images and should run natively. A docker-compose.override.yml in the project root does the trick:

```yaml
services:
  # amd64-only images -> run under emulation
  php:            { platform: linux/amd64 }
  fpm:            { platform: linux/amd64 }
  node:           { platform: linux/amd64 }
  selenium:       { platform: linux/amd64 }
  pubsub-emulator: { platform: linux/amd64 }  # google/cloud-sdk:375.0.0-emulators is amd64-only

  # native arm64 -> avoids the ES seccomp crash
  elasticsearch:  { platform: linux/arm64 }
  mysql:          { platform: linux/arm64 }
  object-storage: { platform: linux/arm64 }
  httpd:          { platform: linux/arm64 }
  blackfire:      { platform: linux/arm64 }
``` 

Notes:
- Do not also set `DOCKER_DEFAULT_PLATFORM=linux/amd64`, it overrides the arm64 pins and reintroduces the ES crash.
- If ES was previously pulled as amd64, remove the cached image so the arm64 one is fetched: `docker rmi elastic/elasticsearch:8.17.0`.
- `google/cloud-sdk:375.0.0-emulators` has no arm64 manifest, hence the amd64 pin for pubsub-emulator.

With this override, make prod completes cleanly and the PIM comes up at `http://localhost:8080.`

Environment

- Apple Silicon Mac, Docker Desktop
- akeneo/pim-community-standard v2026.3 (php-dev 8.3, ES 8.17.0, MySQL 8.0.34)

This is only a stopgap, native arm64 builds of pim-php-dev and node (the ask in this issue) would remove the emulation entirely. Happy to help test arm64 images if/when they're available.
