### ISSUE TITLE
Configuration of localization is not taken in account

### ISSUE THREAD

**Issue by diglin** [akeneo/pim-community-dev#2068]
The only way to change the interface language is by changing the parameter.yml and the locale to de for german or to fr for french.

If I try to use the configuration located into the menu System > Configuration, the language is never changed even I log out or delete the Akeneo cache

By the way, it will be also great that each user can have his own interface language

**Comment by nidup** [comment]
Hi @diglin,
Thank you for the feedback !
On which version do you encounter the language switching issue ? With a prod or dev install ?
100% agree for the language of the UI per user, this enhancement is in our roadmap.

**Comment by diglin** [comment]
Hi @nidup 

Great that we are agree ;-)

I encounter the issue on a prod install with the latest version 1.2.22

**Comment by noglitchyo** [comment]
Hello, same issue here with 1.3.22!

If I change the language using the UI, it is not working. However, when I change the language into the parameters.yml, it works fine.

**Comment by nidup** [comment]
Hello noglitchyo,

Thank you for the feedback!

It's a well known issue (it will be fixed in 1.4.2), can you check if you have an 'installed' param in your parameters.yml ?

FYI, the following listener forbids to change the locale from the UI when this param is not defined  https://github.com/akeneo/platform/blob/pim-1.3/src/Oro/Bundle/LocaleBundle/EventListener/LocaleListener.php#L43

**Comment by noglitchyo** [comment]
Thanks for your quick answer @nidup 
I check if the **installed** param was in my **parameters.yml**. It wasn't. 
With the **installed: true** in **parameters.yml**, it works like a charm.

Thank you.

**Comment by roldan** [comment]
Hi,

I'm facing the same issue with 'akeneo/pim-community-dev v3.0.8'. This is my parameters.yml:
```
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: dbname
    database_user: dbuser
    database_password: 'password'
    locale: es
    secret: safj3298fj2398fj389fj239d23
    product_index_name: akeneo_pim_product
    product_model_index_name: akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts: 'localhost: 9200'
    installed: true
```
This is the configured language:
![Screenshot from 2019-04-23 23-26-46](https://user-images.githubusercontent.com/695904/56628215-5229c800-661f-11e9-945c-3b5f150999c9.png)

I've tried completely removing cache but with no success. Also adding the "installed" Any hint? 

Thanks!
Matías
