### ISSUE TITLE
Attribute creation

### ISSUE THREAD

**Issue by aRn0D** [akeneo/pim-community-dev#2167]
I have the following fixtures :    
``` yaml
my_code:
        labels:
            fr_FR: Mu label
        type:                pim_catalog_number
        group:               details
        decimalsAllowed:     false
        negativeAllowed:     false
        sortOrder:           210
```
I ran the command `pim:install:db` and my attribute well created but when I wanted to save its value a decimal is stored in the database. Is it a bug or did I do something wrong?
