### ISSUE TITLE
Product import with custom attributes on Category

### ISSUE THREAD

**Issue by BatsaxIV** [akeneo/pim-community-dev#2232]
Hi,

I'm facing a problem with a custom category entity and product import.

I've created a custom category with the related cookbook (http://docs.akeneo.com/1.2/cookbook/category/add-properties-to-category.html) and everything is working fine.

Except when I'm trying to insert a large product import file (through the standard akeneo csv product connector), I'm getting an error : 
> A new entity was found through the relationship 'Pim\Bundle\CatalogBundle\Model\Product#categories' that was not configured to cascade persist operations for entity: [10]. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

I've seen this issue : https://github.com/akeneo/pim-community-dev/issues/1813 which was dealing with the same problem, but the solution is a bit odd to me (adding a cascad: persist on the .yml for the category). Nonetheless, I've tried it and it's not working eitheir.

I've made some empirical test : 
. each row is linked to one or more categories 
. the first 100 rows (2 to 101)are correctly inserted
. the next row (102) triggers the error

I've seen a batch size = 100 in item step, but I can't figure out what is wrong.

*PIM CE v.1.2.29*

Thanks,
Jérémy.

**Comment by BatsaxIV** [comment]
I've tested from a brand new PIM installation (1.2.29), creating only a custom Category entity and relauching pim:installer:db.

File MyCategory.orm.yml : 
```
Acme\CatalogBundle\Entity\MyCategory:
    type: entity
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\CategoryRepository
    fields:
        description:
            type: text
            nullable: true
```

File MyCategory.php : 
```
<?php

namespace Acme\CatalogBundle\Entity;

use Pim\Bundle\CatalogBundle\Entity\Category;

class MyCategory extends Category
{
    protected $description;

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }
}
```

File entities.yml : 
```
parameters:
    pim_catalog.entity.category.class:      Acme\CatalogBundle\Entity\MyCategory
```

The task fails with the same error : 
> An error occured during the fixtures execution.
Error #0 in class Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Pim\Bundle\CatalogBundle\Model\Product#categories' that was not configured to cascade persist operations for entity: [tshirts]. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
#0 /var/www/pim-test/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(797): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Acme\CatalogBundle\Entity\MyCategory))
#1 /var/www/pim-test/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(679): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Doctrine\ORM\PersistentCollection))
#2 /var/www/pim-test/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(404): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Pim\Bundle\CatalogBundle\Model\Product))
#3 /var/www/pim-test/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(703): Doctrine\ORM\UnitOfWork->computeScheduleInsertsChangeSets()
#4 /var/www/pim-test/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(297): Doctrine\ORM\UnitOfWork->computeChangeSets()
#5 /var/www/pim-test/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(389): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /var/www/pim-test/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Manager/ProductManager.php(301): Doctrine\ORM\EntityManager->flush()

**Comment by BatsaxIV** [comment]
File MyCategory.orm.yml with cascade/persist :

```
Acme\CatalogBundle\Entity\MyCategory:
    type: entity
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\CategoryRepository
    fields:
        description:
            type: text
            nullable: true
    cascade:
        - persist
```
Same problem.

Also, same problem on a fresh PIM 1.3.1 install.
