### ISSUE TITLE
Job names on different connectors are unique

### ISSUE THREAD

**Issue by linslin** [akeneo/pim-community-dev#3326]
While configure a job in "batch_jobs.yml", a error comes up. Job names are unique. In that way you can override other jobs by default, example:

```
Connector1:
   jobs:
        my_sweet_export:
Connector2:
   jobs:
     my_sweet_export:
```

So, while creating a new export or Import job by choosing Connector2 - my_sweet_export it will create a job based on Connector1 - my_sweet_export.
