### ISSUE TITLE
Unique attributes written multiple times in the DB

### ISSUE THREAD

**Issue by gplanchat** [akeneo/pim-community-dev#3748]
I'm facing the same issue than in issue #1657

My attribute `sku` (id: 1), the product's unique identifier is saved multiple times :

![image](https://cloud.githubusercontent.com/assets/152367/11766446/b570c06c-a188-11e5-897d-a40cb90edcb9.png)

There is no differences between duplicated rows, excepting the varchar value, sometimes registered as null on one row and correctly filled on the second row, sometimes both rows are correctly filled and strictly identical.

This is my configuration :

``` yml
#Resources/config/batch_jobs.yml
        tft_cached_product_import:
            title: luni_tft_connector.jobs.tft_cached_product_import.title
            type:  import
            steps:
                product_import:
                    title:         luni_tft_connector.jobs.tft_api_import.steps.product_import.title
                    services:
                        reader:    luni_tft_connector.reader.file.product
                        processor: luni_tft_connector.processor.denormalization.product.flat
                        writer:    pim_connector.writer.doctrine.product
                    parameters:
                        batch_size: 10
```

``` yml
#Resources/config/readers.yml
parameters:
    luni_tft_connector.reader.file.product.class: Luni\Component\Connector\Reader\ProductReader # this class is a decorator
services:
    luni_tft_connector.reader.csv_product:
        parent: pim_base_connector.reader.file.csv
    luni_tft_connector.reader.file.product:
        class: '%luni_tft_connector.reader.file.product.class%'
        arguments:
          - '@luni_tft_connector.reader.csv_product'
```

``` yml
#Resources/config/processors.yml
services:
    luni_tft_connector.processor.denormalization.product.flat:
        class: %pim_connector.processor.denormalization.product.class%
        arguments:
            - '@pim_connector.array_converter.flat.product'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.builder.product'
            - '@pim_catalog.updater.product'
            - '@pim_catalog.validator.product'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_catalog.comparator.filter.product'
```

The fix I found for now was deleting the extra rows with this request :

``` sql
DELETE FROM pim_catalog_product_value

WHERE id IN (SELECT * FROM (
  SELECT _original.id
  FROM pim_catalog_product_value AS _original
  LEFT JOIN pim_catalog_product_value AS _copy
    ON _original.`entity_id`=_copy.`entity_id`
    AND _original.`attribute_id`=_copy.`attribute_id`
    AND _original.`id`!=_copy.`id`
    AND (_original.`locale_code`=_copy.`locale_code` OR (_original.`locale_code` IS NULL AND _copy.`locale_code` IS NULL))
    AND (_original.`scope_code`=_copy.`scope_code` OR (_original.`scope_code` IS NULL AND _copy.`scope_code` IS NULL))
  WHERE _copy.id IS NOT NULL
  GROUP BY _original.`entity_id`, _original.`attribute_id`
) AS _tmp);
```
