### ISSUE TITLE
Create grid base on Akeneo components

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3837]
This issue should be referenced with this [topic](http://www.akeneo.com/forums/topic/create-grid-base-on-akeneo-components/), until conversation about multichannel grid (because this is another story).

So the main concept is to build custom grid using Akeneo.  During this process I faced with few problems that are not described in documentation.

After I  have built my datagrid I should add custom datasource for it (and based on needs custom hydrator should be added too), and then in this [file](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/DataGridBundle/Resources/config/data_sources.yml) I should duplicate 49 and 60 lines accordingly to my grid datasource compatibility, the same should be done in this [file](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/DataGridBundle/Resources/config/extensions.yml) on 38 line.

Also there should be configured grid listeners and they should look like:

``` yml
    vendor.event_listener.product_grid_before_listener:
        class: %pim_datagrid.event_listener.configure_product_grid_listener.class%
        arguments:
            - '@pim_datagrid.datagrid.configuration.product.context_configurator'
            - '@pim_datagrid.datagrid.configuration.product.columns_configurator'
            - '@pim_datagrid.datagrid.configuration.product.filters_configurator'
            - '@pim_datagrid.datagrid.configuration.product.sorters_configurator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.price-grid, method: buildBefore }

    vendor.event_listener.product_grid_after_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_product_grid.class%
        arguments:
            - [dataLocale]
            - '@oro_datagrid.datagrid.request_params'
            - '@pim_catalog.context.catalog'
            - '@pim_user.context.user'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.price-grid, method: onBuildAfter }
        calls:
            - [setRequest, ['@?request=']]
```

So, my point is, that there is a way to build custom grid(even multichannel) but there should be more detailed documentation.

Regards, Victor.
