### ISSUE TITLE
Add custom ACL resource and configure permissions

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#3948]
Hello, I created custom controller class and want to apply access restriction on it. So according to [Akeneo documentation](http://docs.akeneo.com/1.4/cookbook/acl/define-acl.html) I defined appropriate ACL. Then I wanted to restrict it for some role, so I went to 'System/ Users Management/ Roles'  and it is not visible on tab 'Permissions'. So I tried to figure out how existing permissions list  is included to UI.

I provided some research, and found it to be complicated. I found that it is related to following configuration:

``` yml
oro_user:
    privileges:
        action:
            label: rights.action
            view_type: groups
            types: [action]
            field_type: pim_acl_access_level_selector
            default_value: 5
            show_default: true
```

And it is used by `Oro\Bundle\SecurityBundle\Form\Type\PrivilegeCollectionType`, but I can't find place where all ACL resources are collected for displaying. Or have I omitted something? Could you please clarify a little bit more about how it is working? 

Regards, Victor.
