### ISSUE TITLE
Question: Mass edit error caused by incomplete transchoice-translation in russian. 

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#4227]
If we select more than 4 products and our admin dashboard area is set to russian language we get error caused by incomplete transchoice translation. 

Quick fix is to create ```app/Resources/translations/messages.ru.yml``` and paste there fixing translation like that.

```yml
pim_enrich:
    mass_edit_action:
        product:
            page_subtitle: 'Массовое редактирование (1 продукт)|Массовое редактирование (%count% продуктов)|Массовое редактирование (%count% продуктов)'
``` 

The question: Is it fixed now in 1.5 or translations migrated from EnrichBundle?
