### ISSUE TITLE
Image product never delete ?

### ISSUE THREAD

**Issue by lpxavi** [akeneo/pim-community-dev#4294]
Hi,

I use Akeneo v1.4.22.

I have noticed that product's images are never delete. Neither when delete image of a product nor when we execute a mass product import with image.

It's a bug or it's good ?

Is there a way to delete all image not link at a product ?

Thank's you

**Comment by a2xchip** [comment]
Hello @lpxavi 
This issue seems to be related with #3572 

Here is the @juliensnz answer

> What you try to achieve is already the normal behaviour on Akeneo PIM:
When a media is removed from a product field, we keep it in the media table and keep it on the file system. We only break the relation between the product value and the media in database.

> Did I miss something ?

**Comment by a2xchip** [comment]
@lpxavi See this part of orm mapping

```yml
# ProductValue.orm.yml

Pim\Bundle\CatalogBundle\Model\ProductValue:
    type: entity
    table: pim_catalog_product_value
    changeTrackingPolicy: DEFERRED_EXPLICIT
    # ......
        manyToOne:
        # ........
        media:
            targetEntity: Akeneo\Component\FileStorage\Model\FileInfoInterface
            cascade:
                - remove
                - persist
                - refresh
                - detach
            joinColumns:
                media_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL' # this line
```
