### ISSUE TITLE
L10n date format 

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#4309]
**I'm reporting a Bug** or **I'm asking a Question**

Documentation says that we have to set our php.ini to ```Etc/Utc```. Whatever it means i tried both: our locale ```Europe/Chisinau``` and ```Etc/Utc``` with russian language system settings but it shows dates in wrong format in that formatted places and it shows wrong time in that unformatted like import/export history and so on.

**The question is:**
* Is it bug?
* Or it is wrong php.ini settings?

**Comment by skeleton** [comment]
Hi @a2xchip ,

Inside the PIM, dates are formatted by PHP library http://php.net/manual/fr/class.intldateformatter.php.
If in your account, your locale (to define in My account > tab "Interfaces") is defined as Russian (locale = ru_RU) and dates format provided by IntlDateFormatter are not OK for you, you can update them in the PIM configuration. You can follow this documentation: 
http://docs.akeneo.com/1.5/cookbook/localization/how_to_use_the_presenters.html#how-to-modify-the-predefined-formats-of-default-presenters

Your result should look like:

```
pim_catalog.localization.factory.date.formats:
    en_US: 'MM/dd/yyyy'
    fr_FR: 'dd/MM/yyyy'
    ru_RU: 'dd/MM/yyyy'
pim_catalog.localization.factory.datetime.formats:
    en_US: 'MM/dd/yyyy hh:mm a'
    fr_FR: 'dd/MM/yyyy HH:mm'
    ru_RU: 'dd/MM/yyyy HH:mm'
```
