### ISSUE TITLE
[MethodNameGuesser] Error while guessing the method name for "launchPackages"

### ISSUE THREAD

**Issue by gbalcewicz** [akeneo/pim-community-dev#4448]
While defining reference data (multi) with name `launchPackages` I'm getting `[LogicException] Error while guessing the method name for "launchPackages"` while running `pim:reference-data:check`. This is because the `StringUtil::singularify` returns array of candidates:

```
Array
(
    [0] => launchPackag
    [1] => launchPackage
)
```

It would be nice to have possibility to define singular name in the config (optionally) for such situations, for example:

```
pim_reference_data:
    launchPackages:
        class: AppBundle\Entity\LaunchPackage
        type: multi
        singularName: launchPackage
```

**Comment by gbalcewicz** [comment]
Any update on this? I'd like to also mention that there is another word what I encounter this problem. I've tried to add an reference data (simple) named axis. When saving I'm getting an error: {"status":"error","status_code":500,"status_text":"Internal Server Error","current_content":"","message":"ProductValue method \"setAxi\" is not implemented"}. In this example instead of an array the StringUtil:singularify returns 'axi'.

I think the method name guessing cannot relay on the singularify only.

**Comment by aRn0D** [comment]
Hi Grzegorz,

Didn't you forget to override the product value? You can find more informations about the reference data there : http://docs.akeneo.com/latest/cookbook/catalog_structure/creating_a_reference_data.html?highlight=pim_reference_data

**Comment by gbalcewicz** [comment]
I have override the product value,
```
AppBundle\Entity\ProductValue:
    type: entity
    table: pim_catalog_product_value
    changeTrackingPolicy: DEFERRED_EXPLICIT
    indexes:
        value_idx:
            columns:
                - attribute_id
                - locale_code
                - scope_code
        varchar_idx:
            columns:
                - value_string
        integer_idx:
            columns:
                - value_integer
    manyToOne:
        launchPackage:
            targetEntity: AppBundle\Entity\LaunchPackage
            joinColumn:
                name: launch_package_id
                referencedColumnName: id
    manyToMany:
        launchPackages:
            targetEntity: AppBundle\Entity\LaunchPackage
            cascade:
                - refresh
            joinTable:
                name: app_catalog_product_value_launch_package
                joinColumns:
                    value_id:
                        referencedColumnName: id
                        nullable: true
                        onDelete: CASCADE
                inverseJoinColumns:
                    launch_package_id:
                        referencedColumnName: id
                        nullable: false
```

I have added both for simple and mulit

```
pim_reference_data:
    launchPackage:
        class: AppBundle\Entity\LaunchPackage
        type: simple
    launchPackages:
        class: AppBundle\Entity\LaunchPackage
        type: multi

akeneo_storage_utils:
    mapping_overrides:
        -
            original: Pim\Component\Catalog\Model\ProductValue
            override: AppBundle\Entity\ProductValue
```

Just for the testing purposes I edited the `Pim\Component\ReferenceData\MethodNameGuesser` with

```
public static function guess($prefix, $dataName, $singularify = false)
    {
        $name = $dataName;

        if ($singularify) {
            if ($dataName == 'launchPackages') {
                $name = 'launchPackage';
            } else {
                $name = StringUtil::singularify($dataName);
            }

            if (is_array($name)) {
                throw new \LogicException(
                    sprintf('Error while guessing the method name for "%s"', $dataName)
                );
            }
        }

        $name = ucfirst($name);

        return sprintf('%s%s', $prefix, $name);
    }
```

and all works ok then. Without this change singularify returns an array
```
Array
(
    [0] => launchPackag
    [1] => launchPackage
)
```
what's resulting in throwing `\LogicException`. And this is for the first comment.

For the second one with Axis:
```
pim_reference_data:
    axis:
        class: AppBundle\Entity\Axis
        type: simple
```

Product mapping:
```
manyToOne:
        axis:
            targetEntity: AppBundle\Entity\Axis
            joinColumn:
                name: axis_id
                referencedColumnName: id
```

The singularify is not throwing exception but returning axi (I don't know why it's even trying to singularify if it's simple type) and then we are getting the following error

```
{"status":"error","status_code":500,"status_text":"Internal Server Error","current_content":"","message":"ProductValue method \"setAxi\" is not implemented"}
```

I hope this explains better what is the problem here.
