### ISSUE TITLE
Add LuminousFlux, MassFlowRate, VolumetricFlowRate, Luminance, AreaDensity in Measures

### ISSUE THREAD

**Issue by akazik** [akeneo/pim-community-dev#5062]
In the ElectricCharge definition is an error (https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Bundle/MeasureBundle/Resources/config/measure.yml#L269):
The conversion from COULOMB (all of them) to AMPEREHOUR should be div and not mul. (1C = 1As = 1/3600 Ah). And in the name CENTIOULOMB is the C missing.

**Comment by akazik** [comment]
Additional is MILIBAR short of one L.

**Comment by gplanchat** [comment]
@akazik Are you sure `MILIBAR` has only one L ?

**Comment by a2xchip** [comment]
http://www.abbreviations.com/abbreviation/millibar

**Comment by akazik** [comment]
@gplanchat, @a2xchip I'm sure millibar has two l. In the measures.yml version we still use (1.4/1.5) it's wrong. Didn't see that's already fixed, sorry.

And we've added the following, maybe also interesting:
```
    LuminousFlux:
        standard: LUMEN
        units:
            LUMEN:
                convert: [{'mul': 1}]
                symbol: lm
    MassFlowRate:
        standard: KILOGRAM_PER_SECOND
        units:
            KILOGRAM_PER_SECOND:
                convert: [{'mul': 1}]
                symbol: kg/s
            GRAM_PER_HOUR:
                convert: [{'mul': 3.6}]
                symbol: g/h
    VolumetricFlowRate:
        standard: CUBIC_METER_PER_SECOND
        units:
            CUBIC_METER_PER_SECOND:
                convert: [{'mul': 1}]
                symbol: m³/s
            LITER_PER_MINUTE:
                convert: [{'mul': 0.001}, {'div': 60}]
                symbol: l/m
    Luminance:
        standard: LUMINANCE
        units:
            LUMINANCE:
                convert: [{'mul': 1}]
                symbol: cd/m²
    AreaDensity:
        standard: KILOGRAM_PER_SQUARE_METER
        units:
            KILOGRAM_PER_SQUARE_METER:
                convert: [{'mul': 1}]
                symbol: kg/m²
            GRAM_PER_SQUARE_METER:
                convert: [{'mul': 0.001}]
                symbol: g/m²
```
