### ISSUE TITLE
Importing the same SKU over multiple steps isn't working

### ISSUE THREAD

**Issue by hostep** [akeneo/pim-community-dev#5309]
**I _think_ I'm reporting a Bug**

Hi guys

We have a custom importer module with multiple steps.
In a couple of steps we import some product data, but it happens that we import the same sku over multiple steps. See below for an example, in step 3 (`import_products`) and also in step 4 (`import_product_descriptions`) we can import the same `sku` but  with different attributes.

When we do this, we see these warnings appearing during step 4:
```
values[sku]: The value AABBCC is already set on another product for the unique attribute sku: AABBCC
```

I understand that we can't import the same product in the same step. But I would have expected we can import them over different steps.
Is this supposed to happen or is this a bug?

Using Akeneo CE 1.5.14, for more details:
[akeneo-pim-system-info_2016-12-06_12-51.txt](https://github.com/akeneo/pim-community-dev/files/633761/akeneo-pim-system-info_2016-12-06_12-51.txt)

batch_jobs.yml file (*** was added to hide confidential information):
```yml
connector:
    name: *** Import Connector
    jobs:
        ***_import_from_***:
            title: ***_import_connector.jobs.***_import_from_***.title
            type:  import
            steps:
                download_import_files:
                    title: ***_import_connector.jobs.***_import_from_***.download_import_files.title
                    class: "%***_import_connector.downloader.products.class%"
                    services:
                        xml_handler: ***_import_connector.downloader.handler.xml
                        images_handler: ***_import_connector.downloader.handler.images
                import_attribute_options:
                    title: ***_import_connector.jobs.***_import_from_***.import_attribute_options.title
                    services:
                        reader:    ***_import_connector.reader.file.xml_options
                        processor: pim_connector.processor.denormalization.attribute_option.flat
                        writer:    pim_connector.writer.doctrine.attribute_option
                import_products:
                    title: ***_import_connector.jobs.***_import_from_***.import_products.title
                    services:
                        reader:    ***_import_connector.reader.file.xml_products
                        processor: pim_connector.processor.denormalization.product.flat
                        writer:    pim_connector.writer.doctrine.product
                import_product_descriptions:
                    title: ***_import_connector.jobs.***_import_from_***.import_product_descriptions.title
                    services:
                        reader:    ***_import_connector.reader.file.xml_product_descriptions
                        processor: pim_connector.processor.denormalization.product.flat
                        writer:    pim_connector.writer.doctrine.product
```

Thanks!
