### ISSUE TITLE
Amazon S3 storage - Export as URL

### ISSUE THREAD

**Issue by theangryangel** [akeneo/pim-community-dev#5540]
As advised in #technical of slack, I'm logging this issue.

### Background
Currently we're testing Akeneo, and using [S3](https://docs.akeneo.com/1.6/cookbook/product_asset/how_to_connect_to_an_external_server.html) to store our assets.

When we do an export and tell it to include files, it _appears_ (I'll be honest I've not gone digging into this very hard) that Akeneo redownloads all of the assets. Which isn't practical for us.

If we don't enable the "Export Files and Images" option the attributes aren't included in the export. Which is a problem.

### Proposal

What I'd like is to provide a path or URL in the export, exactly like the API currently does (which I'm using for something else).

Provisionally I was thinking to add something like this on the export profile, so that the CSV would contain the attributes with `https://cloudfront..../catalog/a/b/c/0/0000/whatever.jpg`
![basmiq](https://cloud.githubusercontent.com/assets/309967/22107733/67fcd5e4-de47-11e6-9f3d-c51c999904d3.png)

I *think* this is something I can put together and provide a PR for (I may require guidance on the specs). The question is, would you be likely to accept it if I did?

**Comment by gplanchat** [comment]
I think you could simply use a `Pim\Component\Connector\Writer\File\Csv\Writer` instead of the `Pim\Component\Connector\Writer\File\Csv\ProductWriter` for your CSV writer.

**Comment by theangryangel** [comment]
I'll prefix this by saying, until now I was just using the using the GUI to define my exports, rather than anything else. My test export is using the `csv_product_export` job, with the `Akeneo CSV Connector`.

After doing some more reading of [the docs](https://docs.akeneo.com/1.6/reference/import_export/product-export.html), and where necessary grep'ing through the distribution zip. I *think* I understand that I need to define some new jobs, steps, etc.

So I *think* I need something like this in `app/config.yml` under `services:`
```
    ## Custom CSV export
    pim_connector.job.job_parameters.default_values_provider.product_csv_export:
        class: Pim\Component\Connector\Job\JobParameters\DefaultValuesProvider\ProductCsvExport
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.simple_csv_export'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            -
                - 'my_csv_product_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_connector.step.my_csv_product.export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product'
            - '@pim_connector.processor.normalization.product'
            - Pim\Component\Connector\Writer\File\Csv\Writer
            - 10

    pim_connector.job.my_csv_product_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'my_csv_product_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.csv_product.export'
        tags:
            - { name: akeneo_batch.job, connector: 'My CSV Product Export', type: 'export' }
```

Which after a cache clear tells me I now need to create a form. Which I'm kinda having difficulty tracking at this point, and I'm starting to wonder if:
1. I'm over complicating or missing something?
2. Is the trail of yml going to end?
3. To my untrained eye, it looks like the `@pim_connector.processor.normalization.product` or [Pim\Component\Connector\Processor\Normalization\ProductProcessor](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php) is really whats causing my problem (since that seems to be what is stripping out the content) and I can't figure out the ramifications of removing that from my `pim_connector.step.my_csv_product.export` definition
