### ISSUE TITLE
Cannot create route in the menu without prefixing its name by `pim_`

### ISSUE THREAD

**Issue by gplanchat** [akeneo/pim-community-dev#7158]
Menu elements having a route which name isn't starting with `pim_` does not fire an HTTP request.

This works:

```yaml
extensions:
    foo-menu:
        module: pim/menu/tab
        parent: pim-menu
        position: 25
        targetZone: mainMenu
        config:
            title: foo.tab.menu_item
            iconModifier: iconFoo

    foo-menu-column:
        module: pim/menu/column
        parent: pim-menu
        position: 100
        targetZone: column
        config:
            stateCode: foo-menu
            tab: foo-menu
            navigationTitle: foo.navigation.title

    foo-menu-navigation-block-management:
        module: pim/menu/navigation-block
        parent: foo-menu-column
        position: 50
        targetZone: navigation
        config:
            title: foo.navigation.title

    foo-menu-dashboard:
        module: pim/menu/item
        parent: foo-menu-navigation-block-management
        position: 100
        config:
            title: foo.navigation.dashboard
            to: pim_foo_index
```

This doesn't work (note the route renamed from `pim_foo_index` to `foo_index`): 

```yaml
extensions:
    foo-menu:
        module: pim/menu/tab
        parent: pim-menu
        position: 25
        targetZone: mainMenu
        config:
            title: foo.tab.menu_item
            iconModifier: iconFoo

    foo-menu-column:
        module: pim/menu/column
        parent: pim-menu
        position: 100
        targetZone: column
        config:
            stateCode: foo-menu
            tab: foo-menu
            navigationTitle: foo.navigation.title

    foo-menu-navigation-block-management:
        module: pim/menu/navigation-block
        parent: foo-menu-column
        position: 50
        targetZone: navigation
        config:
            title: foo.navigation.title

    foo-menu-dashboard:
        module: pim/menu/item
        parent: foo-menu-navigation-block-management
        position: 100
        config:
            title: foo.navigation.dashboard
            to: foo_index
```

I thought it could come from `FOSJsRoutingBundle` which have a `fos_js_routing.routes_to_expose` config, I'm not sure about it. I hope it would be easier to register new routes with a simple way to register them.
