### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory error upon installation

### ISSUE THREAD

**Issue by lferrao** [akeneo/pim-community-dev#7504]
Hi,

I just installed 2.1 CE following this guide:
https://docs.akeneo.com/2.0/install_pim/docker/installation_docker.html

Everything went well with no errors, the cache folders were correctly chowned to docker and node users, after running pim-dependencies.sh successfully running pim-initilaize.sh will trigger the error in the title in PimRequirements.php line 250.

I was able to reproduce this both in Ubuntu 16.07 as well as CoreOS.

The MYSQL container appears to be up and running, docker-compose.yml is the default dist one, here's my parameters.yml:

```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: akeneo_pim
    database_user: akeneo_pim
    database_password: akeneo_pim
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    product_index_name: akeneo_pim_product
    product_model_index_name: akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts: 'localhost: 9200'
```

ps:

```
       Name                      Command               State                 Ports
------------------------------------------------------------------------------------------------
pim_elasticsearch_1   /bin/bash bin/es-docker          Up       0.0.0.0:9200->9200/tcp, 9300/tcp
pim_fpm_1             /usr/local/bin/entrypoint. ...   Up
pim_httpd_1           httpd-foreground                 Up       0.0.0.0:8080->80/tcp
pim_mysql_1           docker-entrypoint.sh mysqld      Up       0.0.0.0:3306->3306/tcp
pim_node_1            node                             Exit 0
```
