### ISSUE TITLE
How to run the rules for Product model attributes ?

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [akeneo/pim-community-dev#7711]
Hi,

I'm using Akeneo 2.0.15 Enterprise edition. I have written a rule to copy the description en-US attribute values to description de-DE attribute value. I'm using the same attribute to product and product model.

When I execute the rule, only product description de-DE will update the values. Product model will not get affected. How to run the rule for Product Model?

**Comment by Delphineray** [comment]
Hello,

The application of rules is not available on the product models' values, only on the products' values, it will be available in our next 2.2 release, available at the end of March.

Regards,
Delphine

**Comment by Vanitha-bujjinga** [comment]
@Delphineray Thank you for the update.

**Comment by EricPaulson** [comment]
I have 2.2 and I am not finding the ability to add rules to product models. @Delphineray, can you point me in the right direction?

**Comment by Delphineray** [comment]
Hello @EricPaulson, 

It's the same than for products, you define rules on attributes using a YML file (dedicated import job "yml_rule_import") and if rules are applied on common attributes for products with variants, they will be applied on product models.
You can have more details here: https://help.akeneo.com/articles/manage-your-rules.html

Regards,
Delphine

**Comment by EricPaulson** [comment]
@Delphineray, I have an attribute that belongs to the product model. When that attribute is changed, I have a rule that copies the value to another attribute on the product model. That is not firing when the rule is executed. Here is my YML that I imported for the rule:

```
rules:
    create_slug:
        priority: 0
        conditions:
            - field: slug
              scope: realtruck
              operator: EMPTY
        actions:
            - type: slug
              fromField: productLineName
              toField: slug
              options:
                  scope: realtruck
                  locale: null
```

Note that I have created a custom rule called 'slug'. This works fine if the attribute belongs to a product, but if it's on a product model, it does not work.
