### ISSUE TITLE
[2.2.1] Unrecognized option "client" under "oneup_flysystem.adapters.catalog_storage_adapter.awss3v3"

### ISSUE THREAD

**Issue by chrishodgsonplt** [akeneo/pim-community-dev#7865]
I believe this is a bug. I am using the latest version of akeneo 

**```Unrecognized option "client" under "oneup_flysystem.adapters.catalog_storage_adapter.awss3v3"```**

in **composer.lock**:
```
akeneo/pim-community-dev: v2.2.1,
symfony/symfony: v3.4.2
oneup/flysystem-bundle: 1.14.0
aws/aws-sdk-php: 3.52.31
league/flysystem-aws-s3-v3: 1.0.40
```

in **services.yml**:
```
services:
  app.amazon.s3_client:
    class: Aws\S3\S3Client
    arguments:
      -
        credentials:
          key: MY_KEY
          secret: MY_SECRET
        version: latest
        region: eu-west-1
```
in **config.yml**:
```
oneup_flysystem:
  adapters:
    catalog_storage_adapter:
      awss3v3:
        client: app.amazon.s3_client
        bucket: ~
        prefix: ~
```
