### ISSUE TITLE
API: Problem with slashes in identifiers yet again, but this time for the `/product-models` GET API

### ISSUE THREAD

**Issue by ishasaran** [akeneo/pim-community-dev#9141]
Hi there,

This is a recurring problem from the fix that was deployed which has the introduction of the `requirement` as an option to specify a regex for allowing a certain character(s), in the identifiers of the api. The identifiers has slashes ("/").

**Expected behaviour**
To allow the slashes ("/") when hitting the GET API for `/product-models/{code}`, where the `code` identifier can be allowed any character(s) using `requirements` option for `code`, in the YML as,
```
pim_api_product_model_get:
  path: /product-models/{code}
    defaults: { _controller: pim_api.controller.product_model:getAction, _format: json }
    methods: [GET]
    requirements:
        code: .+
```

**The problem**
As mentioned as the solution (https://bit.ly/2qYaLH7) to the issue #6264, we tried adding the `requirement` to our api,
`/api/rest/v1/product-models/{our-product-model-code}`

but we encounter the following error as response,
```
{
    "code": 404,
    "message": "No route found for \"GET /api/rest/v1/product-models/{our-product-model-code}\""
}
```

**Steps to reproduce**
Please be advised to test with the GET a product model API for the PIM (https://api.akeneo.com/api-reference-22.html#get_product_models__code_)
