### ISSUE TITLE
Aws s3 question

### ISSUE THREAD

**Issue by mauroandres** [akeneo/pim-community-dev#9189]
Hi, I'm using akeneo pim 2.3.
I configure aws s3 bucket.
The images are stored in as3 but the urls always are:
"pim-url/media/show/...some_image.jpg"
I am doing something wrong?

app/config/config.yml (this config is ok?)
```
oneup_flysystem:
    adapters:
        catalog_storage_adapter:
            awss3v3:
                client: acme.s3_client
                bucket: somebucket
                prefix: media
        asset_storage_adapter:
            awss3v3:
                client: acme.s3_client
                bucket: somebucket
                prefix: media

```
services.yml
```
    acme.s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                version: '2006-03-01'
                region: "us-east-1"
                credentials:
                    key: "KEY"
                    secret: "secret"
```
