### ISSUE TITLE
Edit button disappers when I disable permission to Edit Users on my account page

### ISSUE THREAD

**Issue by amitvkhajanchi** [akeneo/pim-community-dev#9422]
**I'm reporting a Bug**

The expected behavior is that Admin can change roles for users.   Regular users can be of category -> Catalog Managers (they can do various pim edits), and Users, they should only view products and export export but not import etc.  But only Admin should change System settings.

When I remove the system permission entirely from Catalog managers and Users, then these users no longer see the "Edit" button when they go to my accounts.   I have to enable Edit Users permission in Roles to enable this.. but if I do this, then they can self-assign different roles to themselves.. which is not correct.

Interestingly, when I remove above permission, although I don't have Edit button visible in my regular users account page, but when I have them go to http://domain/#/user/profile/edit they can update their preferences etc.. and save and Groups and Roles tab is visible but not editable.  This actually is correct behavior, so it seems only issue is that the Edit Button on my accounts page also gets hidden (this is incorrect behavior) unless I enable Edits Users permission under Sytem for the Role (which is not desired).

Any user should be able to change their profile preferences in General, Additional, Interfaces, Password tabs, but should only have view permission for Groups and Roles they are part of.

**Comment by amitvkhajanchi** [comment]
I am using Version 2.3.24 CE edition of Akeneo.

**Comment by Doodoune** [comment]
Hi!
Actually, a user that has permission to "Edit users" can edit **all** users. But we don't have a right specific like "Edit my profile". 
I linked your issue to our improvement ticket (internal reference IM-1083) about creating this new role.
We will keep you updated about his prioritization.
Regards,

**Comment by ptitkosmos** [comment]
Any update ?

**Comment by Doodoune** [comment]
Hi @ptitkosmos, 
It still not prioritizes. We will keep you updated,
Regards,

**Comment by ptitkosmos** [comment]
As a workaround to let user edit their profile without giving them the direct link : 
Give them "edit user acl".
Create a new acl or use current edit role acl
```
# Custom edit acl
pim_enrich_category_edit_user_role:
    type: action
    label: pim_enrich.acl.user.edit_user_role
    group_name: pim_enrich.acl_group.user
```
Add a resource config file : 
```
# view_elements\user.yml
services:
  pim_user.view_element.user.tab.group_and_role:
    parent: pim_enrich.view_element.base
    arguments:
      - 'pim_user.user.tab.group_and_role'
      - '%pim_user.view_element.user.tab.group_and_role.template%'
    calls:
      - [ addVisibilityChecker, ['@pim_user.view_element.visibility_checker.groups_and_roles'] ]
      - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.acl', {acl: 'pim_enrich_category_edit_user_role'}] ]
    tags:
      - { name: pim_enrich.view_element, type: pim_user_user_form.form_tab, position: 110 }
```
Add this file in your dependancy injection `$loader->load('view_elements/user.yml');`

/!\ User can change other user data (but not their password) by editing the url directly
